CREATE DATABASE BDLojaDeGame;
USE BDLojaDeGame;

CREATE TABLE TBCliente(
CPFCli VARCHAR(14) PRIMARY KEY,
NomeCli VARCHAR(100) NOT NULL,
DatNascCli VARCHAR(10) NOT NULL,
EnderecoCli VARCHAR(150) NOT NULL,
CelularCli  VARCHAR(13) NOT NULL,
EmailCli VARCHAR(100) NOT NULL
);

CREATE TABLE TBFuncionario(
CodFunc INT PRIMARY KEY,
NomeFunc VARCHAR(100) NOT NULL,
CPFfunc VARCHAR(14) NOT NULL,
NascFunc VARCHAR(10) NOT NULL,
EnderecoFunc VARCHAR(150) NOT NULL,
CelularFunc VARCHAR(13) NOT NULL,
EmailFunc VARCHAR(100) NOT NULL,
CargoFunc VARCHAR(100) NOT NULL
);

CREATE TABLE TBJogo(
CodGame INT PRIMARY KEY,
NomeGame VARCHAR(100) NOT NULL,
VersaoGame VARCHAR(50),
desenvolvedorGame VARCHAR(100) NOT NULL,
GeneroGame VARCHAR(100) NOT NULL,
EtariaGame VARCHAR(2) NOT NULL,
PlataformaGame VARCHAR(150) NOT NULL,
AnoLancamentoGame VARCHAR(4) NOT NULL,
SinopseJogo VARCHAR(250) NOT NULL
);